<?php
// Plugin definition
$plugin = array(
  'title' => t('Radix Brown Pond'),
  'icon' => 'radix_brown_pond.png',
  'category' => t('Radix'),
  'theme' => 'radix_brown_pond',
  'regions' => array(
    'slider' => t('Slider'),
    'slidergutter' => t('Slider Gutter'),
    'widemessage' => t('Message'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'column3' => t('Third Column'),
    'footercolumn1' => t('Footer First Column'),
    'footercolumn2' => t('Footer Second Column'),
    'footercolumn3' => t('Footer Third Column'),
  ),
);
